logo = "/uploads/logo-of-zblogging.png"
icon = "/uploads/zblogging-favicon.png"
description = "Top Unbiased Kitchen Products Reviews & Buying Guides"
contacteMail = "hamzajaani143@gmail.com"

[open_graph]
excrept = "If you are a newbie and looking for the best blog to learn Learn Digital Marketing and Blogging then zBlogging is the best place to Learn Blogging for Free.\n"
facebookPublisher = ""
facebookAuthor = ""
twitterPublisher = ""
twitterAuthor = ""
image = ""

[verifications]
PinterestVerify = ""
googleSiteVerify = ""
BingWebmaster = ""
YandexVerify = ""

[siteAuthor]
name = "Hamza Hashim"
avatar = ""
bio = "This is Mark, I am a passionate blogger and love to review new products for daily use."

[social_accounts]
sitefbAccount = "https://www.facebook.com/reviewtek"
sitetwitterAccount = ""
siteinstagramAccount = ""
sitepinterestAccount = ""