logo = "/uploads/reviews-tek-logo.png"
icon = "/uploads/favicon.png"
description = "Top Unbiased Kitchen Products Reviews & Buying Guides"
contacteMail = "contact@reviewstek.com"

[open_graph]
excrept = "At Reviews Tek, we provide Top Unbiased Home & Kitchen Products Reviews & Buying Guides, and comparison charts are just a few things we offer to help you find the best available product in the market."
facebookPublisher = "reviewstek"
facebookAuthor = "reviewstek"
twitterPublisher = "reviewstek"
twitterAuthor = "reviewstek"
image = "/uploads/reviewstek_cover.png"

[verifications]
PinterestVerify = "1fd9d971d18c32f55134165f30b04cfd"
googleSiteVerify = "qNyQQCBTeTo5eZYmYNK2wqqO0FeOM6TkvmVAwgkeCwY"
BingWebmaster = "E842FE084CF7EFAD862AD9A8494E086E"
YandexVerify = "653a1d9612d4eba2"

[siteAuthor]
name = "Mark Durani"
avatar = "/uploads/mark.jpg"
bio = "This is Mark, I am a passionate blogger and love to review new products for daily use."

[social_accounts]
sitefbAccount = "https://www.facebook.com/reviewtek"
sitetwitterAccount = "https://twitter.com/ReviewsTek"
siteinstagramAccount = "https://www.instagram.com/reviewstek/"
sitepinterestAccount = "https://www.pinterest.com/reviewstek/"