logo = "/uploads/logo-of-zblogging.png"
icon = "/uploads/zblogging-favicon.png"
description = "Learn Digital Marketing and Blogging"
contacteMail = "hamzajaani143@gmail.com"

[open_graph]
excrept = "If you are a newbie and looking for the best blog to learn Learn Digital Marketing and Blogging then zBlogging is the best place to Learn Blogging for Free.\n"
facebookPublisher = ""
facebookAuthor = ""
twitterPublisher = ""
twitterAuthor = ""
image = ""

[verifications]
PinterestVerify = ""
googleSiteVerify = ""
BingWebmaster = ""
YandexVerify = ""

[siteAuthor]
name = "Hamza Hashim"
avatar = ""
bio = "Hamza Hashim the founder of zBlogging. He has appeared on BeingGuru, SEOblog, 4seohelp. Over 4 years of experience he has been doing blogging and SEO. He has helped a lot of businesses to get high visibility on search engines as well on social media platforms."
authorFB = "https://facebook.com/mhamzahashim"
authortwitter = "https://twitter.com/mhamza_hashim"

[social_accounts]
sitefbAccount = ""
sitetwitterAccount = ""
siteinstagramAccount = ""
sitepinterestAccount = ""